### ISSUE TITLE
US3 Add UI (button + view of endorsed text) for endorsing posts

### ISSUE THREAD

**Issue by lukenalewajk** [CMU-313/nodebb-f24-team-software-stars#10]
Effort: low
Acceptance Criteria: An admin can see and click on a button that will mark the topic/main post as endorsed. A non-admin will not see this button. An endorsed post will have a label/UI stating that it is endorsed.

**Comment by ldlin1** [comment]
This is a duplicate of #11

**Comment by veronicabenedict** [comment]
This feature (US3) will be implemented if we hit a roadblock for implementing US1. Else, this issue will be closed as not planned before the end of sprint 2.
