### ISSUE TITLE
US6 Create UI of dashboard for TA response rate

### ISSUE THREAD

**Issue by lukenalewajk** [CMU-313/nodebb-f24-team-software-stars#16]
Effort: medium
Acceptance Criteria: be able to see a display for the TA statistics

**Comment by veronicabenedict** [comment]
Effort: medium 
Acceptance Rate: be able to see a display for the TA statistics

**Comment by veronicabenedict** [comment]
We are closing this issue because we do not have time to implement this task in sprint 2.
