### ISSUE TITLE
US7 Create UI for poll creation 

### ISSUE THREAD

**Issue by lukenalewajk** [CMU-313/nodebb-f24-team-software-stars#18]
Effort: medium
Acceptance Rate: have a separate tab in the UI for poll creation and can be used to create the poll

**Comment by veronicabenedict** [comment]
We are closing this issue because we do not have time to implement this task in sprint 2.

**Comment by etong11** [comment]
Closing issue as we no longer plan to implement it in sprint 2 due to narrowing of scope.
