### ISSUE TITLE
US1 Integrate/hook up "Make Post Anonymous" button to back-end code

### ISSUE THREAD

**Issue by etong11** [CMU-313/nodebb-f24-team-software-stars#30]
Effort: low to medium
Acceptance Criteria: Using the anonymous button when creating a new post/topic will create a new post that is marked anonymous. Other posts that aren't marked anonymous upon creation still showcase user information/is not anonymous.

**Comment by ldlin1** [comment]
We originally worked on this user story during Sprint 1 but found that the permissions and backend logic associated were too difficult to work with, so we shifted away toward US2 and US3 instead.
