### ISSUE TITLE
US1 Add permissions/privileges to anonymous post viewing for admins

### ISSUE THREAD

**Issue by etong11** [CMU-313/nodebb-f24-team-software-stars#32]
Effort: medium to high
Acceptance Criteria: Admins can see the author/user information for an anonymous post. Non-admin users see the post author as anonymous.

**Comment by ldlin1** [comment]
We originally worked on this user story during Sprint 1 but found that the permissions and backend logic associated were too difficult to work with, so we shifted away toward US2 and US3 instead.
