### ISSUE TITLE
US1 Hide anonymous posts from a user's profile

### ISSUE THREAD

**Issue by etong11** [CMU-313/nodebb-f24-team-software-stars#33]
Effort: Medium to high
Acceptance Criteria: When looking at a user's profile in the Posts section, any anonymous posts the user created should not be seen.

**Comment by ldlin1** [comment]
We originally worked on this user story during Sprint 1 but found that the permissions and backend logic associated were too difficult to work with, so we shifted away toward US2 and US3 instead.
