### ISSUE TITLE
US1 Add back-end logic of hiding post author from non-teaching staff (anonymous posting)

### ISSUE THREAD

**Issue by veronicabenedict** [CMU-313/nodebb-f24-team-software-stars#4]
Effort: low to medium
Acceptance Criteria: Creating an anonymous post and checking that non-teaching staff cannot view author but teaching staff can

**Comment by ldlin1** [comment]
We originally worked on this user story during Sprint 1 but found that the permissions and backend logic associated were too difficult to work with, so we shifted away toward US2 and US3 instead.
