### ISSUE TITLE
US2 Add UI change for answered/unanswered questions by a professor

### ISSUE THREAD

**Issue by veronicabenedict** [CMU-313/nodebb-f24-team-software-stars#7]
Effort: low to medium
Acceptance Criteria: a post being shown as unanswered when no professor has added a post to it, and then a professor adding a post and the topic now being shown as answered

**Comment by veronicabenedict** [comment]
Effort: Low
Acceptance Criteria: be able to see which replies have been unanswered and answered

**Comment by etong11** [comment]
Duplicate of #8 - Combining UI change issue with the back-end feature so that back-end code can be developed and tested through front-end UI

**Comment by veronicabenedict** [comment]
this issue is closed. the UI change will be worked on through the issue #8 (comment has been added there)
