### ISSUE TITLE
US2 Add back-end logic and UI change of when a question is marked as answered/unanswered by a professor

### ISSUE THREAD

**Issue by lukenalewajk** [CMU-313/nodebb-f24-team-software-stars#8]
Effort: low to medium
Acceptance Criteria: a post being unanswered when no professor has added a post to it, and then a professor adding a post and the topic now being answered

**Comment by veronicabenedict** [comment]
Effort: low to medium

**Comment by veronicabenedict** [comment]
UI change will also be implemented with this issue from issue #7 (which has now been closed)
