### ISSUE TITLE
US3 Add filtering/tag for unanswered questions

### ISSUE THREAD

**Issue by lukenalewajk** [CMU-313/nodebb-f24-team-software-stars#9]
Effort: low to medium
Acceptance Criteria: be able to see a filter for whether a question has been answered or not

**Comment by veronicabenedict** [comment]
Effort: low to medium
Acceptance Criteria: be able to see a filter for whether a question has been answered or not

**Comment by etong11** [comment]
Closing issue as we no longer plan to implement it in sprint 2 due to narrowing of scope.
